version: '3'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - redis

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    environment:
      - APP_NAME=app
      - APP_PORT=9000
    networks:
      - app-network
    depends_on:
      - app

  db:
    build: .docker/mysql
    command: --innodb-use-native-aio=0
    restart: always
    container_name: db
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=code_micro_videos
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

  redis:
    image: redis:alpine
    networks:
      - app-network
    expose:
      - 6379

networks:
  app-network:
    driver: bridge

